# web port
server:
  port: 8081

  # log config
logging:
  file:
    path: logs/xxl-job
    name: ${logging.file.path}/xxl-job-executor.log
  pattern:
    console: "%date %contextName [%thread] %-5level %logger{36} - %msg%n"
    file: "%date %level [%thread] %logger{36} [%file : %line] %msg%n"

xxl:
  job:
    admin:
      # 注意这里 要和 xxl-job [server.servlet.context-path] 配置对应，此例应设置为 [=/]
      addresses: http://127.0.0.1:8080
      # [xxl.job.accessToken] 设置为空
      username: admin
      password: 123456
      update: true
    executor:
      appName: integration
      title: integration
      address:
      ip:
      port: 9999
      logPath: ${logging.file.path}/integration
      logRetentionDays: 30
    accessToken:

